name: Build
on: [push, pull_request]
env:
  LINK_JOBS: 16
  JOBS: 16

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            name: Windows (x64)
            plat: windows
            arch: x64

          - os: windows-latest
            name: Windows (x86)
            plat: windows
            arch: x86

          - os: windows-latest
            name: Windows (Arm64)
            plat: windows
            arch: arm64

          - os: ubuntu-latest
            name: Linux (x64)
            plat: linux
            arch: x64

          - os: ubuntu-latest
            name: Linux (Arm64)
            plat: linux
            arch: arm64
            triplet: aarch64-linux-gnu
            libc_arch: arm64

          - os: ubuntu-latest
            name: Linux (Arm32)
            plat: linux
            arch: arm32
            triplet: arm-linux-gnueabihf
            libc_arch: armhf

          - os: ubuntu-latest
            name: Linux (PPC64)
            plat: linux
            arch: ppc64le
            triplet: powerpc64le-linux-gnu
            libc_arch: ppc64el

          - os: ubuntu-latest
            name: Linux (RISCV)
            plat: linux
            arch: riscv64
            triplet: riscv64-linux-gnu
            libc_arch: riscv64

          - os: ubuntu-latest
            name: FreeBSD
            plat: freebsd
            arch: x64

          - os: macos-14
            name: MacOS (Arm64)
            plat: macos
            arch: arm64

          - os: macos-13
            name: MacOS (x86)
            plat: macos
            arch: x64

    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install LLVM and Clang
        if: matrix.plat == 'macos-darwin'
        uses: PrimogemStudio/openminecraft-llvm-install@main
        with:
          arm: ${{ matrix.plat == 'macos-darwin' && matrix.arch == 'arm64' }}

      - name: Install xmake
        if: matrix.plat != 'freebsd'
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@master

      - name: Build MacOS
        if: matrix.plat == 'macos-darwin'
        run: |
          xmake f --toolchain=llvm --sdk="${{ env.LLVM_PATH }}" -y
          xmake -y --jobs=${{ env.JOBS }} --linkjobs=${{ env.LINK_JOBS }}

          mv build/macosx build/macos

      - name: Fix MacOS Target Path
        if: ${{ matrix.plat == 'macos-darwin' && matrix.arch == 'x64' }}
        run: |
          mv build/macos/x86_64 build/macos/x64

      - name: Build Linux
        if: ${{ matrix.plat == 'linux' && matrix.arch == 'x64' }}
        run: |
          sudo apt update
          sudo apt install gcc-multilib g++-multilib
          xmake f -a ${{ matrix.arch }} -yc
          xmake -y --jobs=${{ env.JOBS }} --linkjobs=${{ env.LINK_JOBS }}

      - name: Build Linux Cross
        if: ${{ matrix.plat == 'linux' && matrix.arch != 'x64' }}
        run: |
          sudo apt update
          sudo apt install gcc-multilib g++-multilib
          sudo apt install gcc-${{ matrix.triplet }} g++-${{ matrix.triplet }}
          sudo apt install libc6-dev-${{ matrix.libc_arch }}-cross
          xmake f -a ${{ matrix.arch }} --sdk=/usr --cross=${{ matrix.triplet }}- -yc
          xmake -y --jobs=${{ env.JOBS }} --linkjobs=${{ env.LINK_JOBS }}

      - name: Build FreeBSD 
        if: matrix.plat == 'freebsd'
        uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: freebsd
          architecture: x86-64
          version: '13.3'
          memory: 8G
          shell: bash
          environment_variables: LINK_JOBS JOBS
          run: |
            sudo pkg install -y git cmake ninja gmake
            git clone --recursive https://github.com/xmake-io/xmake.git
            cd ./xmake

            /usr/bin/make --version
            ./configure --make=/usr/bin/make
            gmake
            ./scripts/get.sh __local__ __install_only__
            source ~/.xmake/profile
            cd ..

            xmake f -y
            xmake -y --jobs=${{ env.JOBS }} --linkjobs=${{ env.LINK_JOBS }}

            mv build/bsd build/freebsd
            mv build/freebsd/x86_64 build/freebsd/x64

      - name: Configure MSVC
        if: matrix.plat == 'windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build Windows
        if: matrix.plat == 'windows'
        run: |
          xmake f --toolchain=msvc -a ${{ matrix.arch }} -y
          xmake -y --jobs=${{ env.JOBS }} --linkjobs=${{ env.LINK_JOBS }}

      - name: Fix Path
        run: |
          cd build/${{ matrix.plat }}/${{ matrix.arch }}
          mv **.so .
          mv **.dylib .
          mv **.dll .
          cd ../../..

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/
 
