name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            name: Windows (x86_64)
            arch: amd64
            compiler_arch: x86_64
          - os: windows-latest
            name: Windows (x86)
            arch: amd64_x86
            compiler_arch: x86
          - os: windows-latest
            name: Windows (Arm64)
            arch: amd64_arm64
            compiler_arch: arm64
          - os: ubuntu-latest
            name: Linux
          - os: macos-14
            name: MacOS
          - os: macos-13
            name: MacOS (x86)

    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install LLVM and Clang
        if: matrix.os != 'windows-latest'
        uses: PrimogemStudio/openminecraft-llvm-install@main
        with:
          arm: ${{ matrix.os == 'macos-14' }}

      - name: Install xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@master

      - name: Build MacOS
        if: ${{ matrix.os == 'macos-14' || matrix.os == 'macos-13' }}
        run: |
          xmake f --toolchain=llvm --sdk="${{ env.LLVM_PATH }}" -y
          xmake -y -v

      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install gcc-multilib 
          sudo apt install g++-multilib
          sudo apt install g++-aarch64-linux-gnu
          sudo apt install libc6-dev-arm64-cross
          xmake f --toolchain=llvm --sdk="${{ env.LLVM_PATH }}" -yc
          xmake -y -v

      - name: Configure MSVC
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: |
          xmake f --toolchain=msvc -a ${{ matrix.compiler_arch }}
          xmake -y -v
          dumpbin /headers build\windows\x64\release\test.dll

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}-${{ matrix.arch }}
          path: build/
 
