name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            name: Windows (x64)
            plat: windows
            arch: x64

          - os: windows-latest
            name: Windows (x86)
            plat: windows
            arch: x86

          - os: windows-latest
            name: Windows (Arm64)
            plat: windows
            arch: arm64

          - os: ubuntu-latest
            name: Linux
            plat: linux
            arch: x64

          - os: ubuntu-latest
            name: FreeBSD
            plat: freebsd
            arch: x64

          - os: macos-14
            name: MacOS (Arm64)
            plat: macos-darwin
            arch: arm64

          - os: macos-13
            name: MacOS (x86)
            plat: macos-darwin
            arch: x64

    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install LLVM and Clang
        if: matrix.plat == 'macos-darwin'
        uses: PrimogemStudio/openminecraft-llvm-install@main
        with:
          arm: ${{ matrix.plat == 'macos-darwin' && matrix.arch == 'arm64' }}

      - name: Install xmake
        if: matrix.plat != 'freebsd'
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@master

      - name: Build MacOS
        if: matrix.plat == 'macos-darwin'
        run: |
          xmake f --toolchain=llvm --sdk="${{ env.LLVM_PATH }}" -y
          xmake -y

      - name: Build Linux
        if: matrix.plat == 'linux'
        run: |
          sudo apt update
          sudo apt install gcc-multilib 
          sudo apt install g++-multilib
          sudo apt install gcc-aarch64-linux-gnu
          sudo apt install g++-aarch64-linux-gnu
          sudo apt install libc6-dev-arm64-cross
          xmake f -p arm64 --sdk=/usr --cross=aarch64-linux-gnu- -yc
          xmake -y

      - name: Build FreeBSD 
        if: matrix.plat == 'freebsd'
        uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: freebsd
          architecture: x86-64
          version: '13.3'
          memory: 8G
          shell: bash
          environment_variables: ANT_OPTS LWJGL_BUILD_TYPE
          run: |
            sudo pkg install -y git cmake ninja
            git clone --recursive https://github.com/xmake-io/xmake.git
            cd ./xmake

            ./configure --generator=ninja
            gmake
            ./scripts/get.sh __local__ __install_only__
            source ~/.xmake/profile
            cd ..

            xmake f -y
            xmake -y

      - name: Configure MSVC
        if: matrix.plat == 'windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build Windows
        if: matrix.plat == 'windows'
        run: |
          xmake f --toolchain=msvc -a ${{ matrix.arch }}
          xmake -y

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.plat }}-${{ matrix.arch }}
          path: build/
 
