name: Build LWJGL (Android)
on: [push, pull_request]
env:
  ANDROID_NDK_VERSION: r27c

jobs:
  build:
    strategy:
      fail-fast: false

    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Android
        run: |
          git clone https://github.com/LWJGL/lwjgl3
          cd lwjgl3

          wget https://dl.google.com/android/repository/android-ndk-${{ env.ANDROID_NDK_VERSION }}-linux.zip
          unzip android-ndk-${{ env.ANDROID_NDK_VERSION }}-linux.zip

          export ANDROID_NDK_HOME=${{ github.workspace }}/android-ndk-${{ env.ANDROID_NDK_VERSION }}
          
          export LWJGL_BUILD_ARCH=arm64
          ../.ci/build_android.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: lwjgl3/bin/out/